{"timestamp": "2024-11-28T22:46:55.272167", "level": "ERROR", "message": "Error fetching properties: cannot access local variable 'cursor' where it is not associated with a value", "module": "main", "function": "index", "line": 57, "thread_id": 137098883786560, "environment": "development"}
{"timestamp": "2024-11-28T22:47:08.234675", "level": "ERROR", "message": "Authentication error: cannot access local variable 'cursor' where it is not associated with a value", "module": "security", "function": "get_current_user", "line": 102, "thread_id": 137098883786560, "environment": "development"}
{"timestamp": "2024-11-28T22:47:09.083131", "level": "ERROR", "message": "Authentication error: cannot access local variable 'cursor' where it is not associated with a value", "module": "security", "function": "get_current_user", "line": 102, "thread_id": 137098883786560, "environment": "development"}
{"timestamp": "2024-11-28T22:47:29.431685", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 110, "thread_id": 137098883786560, "environment": "development"}
{"timestamp": "2024-11-28T22:47:41.287510", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 110, "thread_id": 137098883786560, "environment": "development"}
{"timestamp": "2024-11-28T22:48:40.251740", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 111, "thread_id": 132637470050112, "environment": "development"}
{"timestamp": "2024-11-28T22:48:52.674925", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 111, "thread_id": 132637470050112, "environment": "development"}
{"timestamp": "2024-11-28T22:55:05.063173", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 111, "thread_id": 139807219496768, "environment": "development"}
{"timestamp": "2024-11-28T22:56:54.301497", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 111, "thread_id": 136082696292160, "environment": "development"}
{"timestamp": "2024-11-28T22:57:07.968586", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 111, "thread_id": 136082696292160, "environment": "development"}
{"timestamp": "2024-11-28T22:58:35.292183", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 111, "thread_id": 135017544652608, "environment": "development"}
{"timestamp": "2024-11-28T22:58:47.240137", "level": "ERROR", "message": "Error fetching properties: cannot access local variable 'cursor' where it is not associated with a value", "module": "main", "function": "index", "line": 36, "thread_id": 136971471755072, "environment": "development"}
{"timestamp": "2024-11-28T22:58:48.740318", "level": "ERROR", "message": "Error fetching properties: cannot access local variable 'cursor' where it is not associated with a value", "module": "main", "function": "index", "line": 36, "thread_id": 136971471755072, "environment": "development"}
{"timestamp": "2024-11-28T22:59:06.352334", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 111, "thread_id": 136971471755072, "environment": "development"}
{"timestamp": "2024-11-28T22:59:27.211031", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 111, "thread_id": 136868065212224, "environment": "development"}
{"timestamp": "2024-11-28T23:01:26.182783", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 111, "thread_id": 140201412593472, "environment": "development"}
{"timestamp": "2024-11-28T23:01:34.323563", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 111, "thread_id": 140201412593472, "environment": "development"}
{"timestamp": "2024-11-28T23:01:52.624632", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 111, "thread_id": 140201412593472, "environment": "development"}
{"timestamp": "2024-11-28T23:03:34.852298", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 115, "thread_id": 134899359663936, "environment": "development"}
{"timestamp": "2024-11-28T23:03:43.976460", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 115, "thread_id": 134899359663936, "environment": "development"}
{"timestamp": "2024-11-28T23:03:48.161223", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 115, "thread_id": 134899359663936, "environment": "development"}
{"timestamp": "2024-11-28T23:03:50.764792", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 115, "thread_id": 134899359663936, "environment": "development"}
{"timestamp": "2024-11-28T23:05:43.680534", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 115, "thread_id": 138745485772608, "environment": "development"}
{"timestamp": "2024-11-28T23:08:16.682561", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 115, "thread_id": 133259676219200, "environment": "development"}
{"timestamp": "2024-11-29T00:30:42.879151", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 115, "thread_id": 127713755305792, "environment": "development"}
{"timestamp": "2024-11-29T00:30:50.816191", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 115, "thread_id": 127713755305792, "environment": "development"}
{"timestamp": "2024-11-29T00:31:08.027418", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 115, "thread_id": 127713755305792, "environment": "development"}
{"timestamp": "2024-11-29T00:33:19.158173", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 102, "thread_id": 127681507399488, "environment": "development"}
{"timestamp": "2024-11-29T00:33:21.572688", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 102, "thread_id": 127681507399488, "environment": "development"}
{"timestamp": "2024-11-29T00:33:21.862841", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 102, "thread_id": 127681507399488, "environment": "development"}
{"timestamp": "2024-11-29T00:33:24.206111", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 102, "thread_id": 127681507399488, "environment": "development"}
{"timestamp": "2024-11-29T00:33:24.572010", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 102, "thread_id": 127681507399488, "environment": "development"}
{"timestamp": "2024-11-29T00:35:19.332995", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 112, "thread_id": 131915789920064, "environment": "development"}
{"timestamp": "2024-11-29T00:35:21.995633", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 112, "thread_id": 131915789920064, "environment": "development"}
{"timestamp": "2024-11-29T00:35:22.703441", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 112, "thread_id": 131915789920064, "environment": "development"}
{"timestamp": "2024-11-29T00:37:23.699860", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 134011918391104, "environment": "development"}
{"timestamp": "2024-11-29T00:37:24.966901", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 134011918391104, "environment": "development"}
{"timestamp": "2024-11-29T00:37:25.622057", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 134011918391104, "environment": "development"}
{"timestamp": "2024-11-29T00:38:24.986791", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 134376837138240, "environment": "development"}
{"timestamp": "2024-11-29T00:38:26.268049", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 134376837138240, "environment": "development"}
{"timestamp": "2024-11-29T00:38:26.988578", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 134376837138240, "environment": "development"}
{"timestamp": "2024-11-29T00:40:22.612512", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 134490709112640, "environment": "development"}
{"timestamp": "2024-11-29T00:40:24.370134", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 134490709112640, "environment": "development"}
{"timestamp": "2024-11-29T00:40:25.095295", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 134490709112640, "environment": "development"}
{"timestamp": "2024-11-29T00:40:27.106206", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 134490709112640, "environment": "development"}
{"timestamp": "2024-11-29T00:40:33.492621", "level": "ERROR", "message": "Error fetching properties: cannot access local variable 'cursor' where it is not associated with a value", "module": "main", "function": "index", "line": 36, "thread_id": 134490709112640, "environment": "development"}
{"timestamp": "2024-11-29T00:40:49.951800", "level": "ERROR", "message": "Login error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "auth", "function": "login", "line": 151, "thread_id": 134490709112640, "environment": "development"}
{"timestamp": "2024-11-29T00:42:02.540093", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 133638968989504, "environment": "development"}
{"timestamp": "2024-11-29T00:42:03.667009", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 133638968989504, "environment": "development"}
{"timestamp": "2024-11-29T00:42:05.958316", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 133638968989504, "environment": "development"}
{"timestamp": "2024-11-29T00:42:06.708960", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 133638968989504, "environment": "development"}
{"timestamp": "2024-11-29T00:42:10.105624", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 133638968989504, "environment": "development"}
{"timestamp": "2024-11-29T00:42:12.241272", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 133638968989504, "environment": "development"}
{"timestamp": "2024-11-29T00:42:12.988559", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 133638968989504, "environment": "development"}
{"timestamp": "2024-11-29T00:43:22.000194", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 131289456224064, "environment": "development"}
{"timestamp": "2024-11-29T00:43:23.515546", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 131289456224064, "environment": "development"}
{"timestamp": "2024-11-29T00:43:24.232000", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 131289456224064, "environment": "development"}
{"timestamp": "2024-11-29T00:43:28.272460", "level": "ERROR", "message": "Error fetching properties: cannot access local variable 'cursor' where it is not associated with a value", "module": "main", "function": "index", "line": 36, "thread_id": 131289456224064, "environment": "development"}
{"timestamp": "2024-11-29T00:43:45.605804", "level": "ERROR", "message": "Login error: cannot access local variable 'cursor' where it is not associated with a value", "module": "auth", "function": "login", "line": 123, "thread_id": 131289456224064, "environment": "development"}
{"timestamp": "2024-11-29T02:21:03.668733", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 131289456224064, "environment": "development"}
{"timestamp": "2024-11-29T02:21:04.454584", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 131289456224064, "environment": "development"}
{"timestamp": "2024-11-29T02:29:53.552126", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 125746901600064, "environment": "development"}
{"timestamp": "2024-11-29T02:29:55.512427", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 125746901600064, "environment": "development"}
{"timestamp": "2024-11-29T02:29:56.252365", "level": "ERROR", "message": "Authentication error: '_GeneratorContextManager' object has no attribute 'cursor'", "module": "security", "function": "get_current_user", "line": 98, "thread_id": 125746901600064, "environment": "development"}
{"timestamp": "2024-11-29T02:35:34.178540", "level": "ERROR", "message": "Dashboard error: 1305 (42000): PROCEDURE real_estate.get_all_properties does not exist", "module": "admin", "function": "admin_dashboard", "line": 48, "thread_id": 129415432787776, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_all_properties does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_all_properties does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 43, in admin_dashboard\n    context[\"properties\"] = execute_procedure(conn, 'get_all_properties')\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 48, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_all_properties does not exist"}}
{"timestamp": "2024-11-29T02:35:35.077679", "level": "ERROR", "message": "Dashboard error: 1305 (42000): PROCEDURE real_estate.get_all_properties does not exist", "module": "admin", "function": "admin_dashboard", "line": 48, "thread_id": 129415432787776, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_all_properties does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_all_properties does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 43, in admin_dashboard\n    context[\"properties\"] = execute_procedure(conn, 'get_all_properties')\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 48, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_all_properties does not exist"}}
{"timestamp": "2024-11-29T02:38:10.054253", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 127414491703104, "environment": "development"}
{"timestamp": "2024-11-29T02:38:13.074969", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 127414491703104, "environment": "development"}
{"timestamp": "2024-11-29T02:38:13.770160", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 127414491703104, "environment": "development"}
{"timestamp": "2024-11-29T02:39:32.639268", "level": "ERROR", "message": "Error fetching properties: 1305 (42000): PROCEDURE real_estate.get_all_properties_with_details does not exist", "module": "main", "function": "index", "line": 36, "thread_id": 136644096210752, "environment": "development"}
{"timestamp": "2024-11-29T02:39:38.319673", "level": "ERROR", "message": "Dashboard error: 1305 (42000): PROCEDURE real_estate.get_admin_dashboard_stats does not exist", "module": "admin", "function": "admin_dashboard", "line": 48, "thread_id": 136644096210752, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_admin_dashboard_stats does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_admin_dashboard_stats does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 38, in admin_dashboard\n    dashboard_stats = execute_procedure(conn, 'get_admin_dashboard_stats')\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 48, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_admin_dashboard_stats does not exist"}}
{"timestamp": "2024-11-29T02:39:38.566837", "level": "ERROR", "message": "Dashboard error: 1305 (42000): PROCEDURE real_estate.get_admin_dashboard_stats does not exist", "module": "admin", "function": "admin_dashboard", "line": 48, "thread_id": 136644096210752, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_admin_dashboard_stats does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_admin_dashboard_stats does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 38, in admin_dashboard\n    dashboard_stats = execute_procedure(conn, 'get_admin_dashboard_stats')\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 48, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_admin_dashboard_stats does not exist"}}
{"timestamp": "2024-11-29T02:40:45.416164", "level": "ERROR", "message": "Dashboard error: 1305 (42000): PROCEDURE real_estate.get_all_agents does not exist", "module": "admin", "function": "admin_dashboard", "line": 48, "thread_id": 126329859495744, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_all_agents does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_all_agents does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 44, in admin_dashboard\n    context[\"agents\"] = execute_procedure(conn, 'get_all_agents')\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 48, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_all_agents does not exist"}}
{"timestamp": "2024-11-29T02:40:47.291074", "level": "ERROR", "message": "Dashboard error: 1305 (42000): PROCEDURE real_estate.get_all_agents does not exist", "module": "admin", "function": "admin_dashboard", "line": 48, "thread_id": 126329859495744, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_all_agents does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_all_agents does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 44, in admin_dashboard\n    context[\"agents\"] = execute_procedure(conn, 'get_all_agents')\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 48, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_all_agents does not exist"}}
{"timestamp": "2024-11-29T02:40:48.649096", "level": "ERROR", "message": "Dashboard error: 1305 (42000): PROCEDURE real_estate.get_all_agents does not exist", "module": "admin", "function": "admin_dashboard", "line": 48, "thread_id": 126329859495744, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_all_agents does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_all_agents does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 44, in admin_dashboard\n    context[\"agents\"] = execute_procedure(conn, 'get_all_agents')\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 48, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_all_agents does not exist"}}
{"timestamp": "2024-11-29T02:41:43.112088", "level": "ERROR", "message": "Error fetching properties: 1305 (42000): PROCEDURE real_estate.get_all_properties_with_details does not exist", "module": "main", "function": "index", "line": 36, "thread_id": 136373047084864, "environment": "development"}
{"timestamp": "2024-11-29T02:41:47.026153", "level": "ERROR", "message": "Authentication error: ", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 136373047084864, "environment": "development"}
{"timestamp": "2024-11-29T02:41:47.793052", "level": "ERROR", "message": "Authentication error: ", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 136373047084864, "environment": "development"}
