{"timestamp": "2024-12-01T14:56:35.492530", "level": "ERROR", "message": "Error in admin_add_property: 1265 (01000): Data truncated for column 'status' at row 1", "module": "admin", "function": "admin_add_property", "line": 447, "thread_id": 129226334742336, "environment": "development", "exception": {"type": "DatabaseError", "message": "1265 (01000): Data truncated for column 'status' at row 1", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Data truncated for column 'status' at row 1\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 388, in admin_add_property\n    property_id_result = execute_procedure(\n                         ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'status' at row 1"}}
{"timestamp": "2024-12-01T15:01:53.881602", "level": "ERROR", "message": "Error in admin_add_property: 1265 (01000): Data truncated for column 'status' at row 1", "module": "admin", "function": "admin_add_property", "line": 448, "thread_id": 137674083014464, "environment": "development", "exception": {"type": "DatabaseError", "message": "1265 (01000): Data truncated for column 'status' at row 1", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Data truncated for column 'status' at row 1\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 389, in admin_add_property\n    property_id_result = execute_procedure(\n                         ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'status' at row 1"}}
{"timestamp": "2024-12-01T15:03:01.995591", "level": "ERROR", "message": "Error in admin_add_property: 1265 (01000): Data truncated for column 'p_status' at row 1", "module": "admin", "function": "admin_add_property", "line": 448, "thread_id": 137674083014464, "environment": "development", "exception": {"type": "DatabaseError", "message": "1265 (01000): Data truncated for column 'p_status' at row 1", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Data truncated for column 'p_status' at row 1\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 389, in admin_add_property\n    property_id_result = execute_procedure(\n                         ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'p_status' at row 1"}}
{"timestamp": "2024-12-01T15:04:39.061644", "level": "ERROR", "message": "Error in admin_add_property: 1265 (01000): Data truncated for column 'p_status' at row 1", "module": "admin", "function": "admin_add_property", "line": 448, "thread_id": 137674083014464, "environment": "development", "exception": {"type": "DatabaseError", "message": "1265 (01000): Data truncated for column 'p_status' at row 1", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Data truncated for column 'p_status' at row 1\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 389, in admin_add_property\n    property_id_result = execute_procedure(\n                         ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'p_status' at row 1"}}
{"timestamp": "2024-12-01T15:07:10.848850", "level": "ERROR", "message": "Error fetching properties: 1305 (42000): PROCEDURE real_estate.get_all_properties_with_details does not exist", "module": "main", "function": "index", "line": 36, "thread_id": 137674083014464, "environment": "development"}
{"timestamp": "2024-12-01T15:07:12.356617", "level": "ERROR", "message": "Error fetching properties: 1305 (42000): PROCEDURE real_estate.get_all_properties_with_details does not exist", "module": "main", "function": "index", "line": 36, "thread_id": 137674083014464, "environment": "development"}
{"timestamp": "2024-12-01T15:07:14.730895", "level": "ERROR", "message": "Error fetching properties: 1305 (42000): PROCEDURE real_estate.get_all_properties_with_details does not exist", "module": "main", "function": "index", "line": 36, "thread_id": 137674083014464, "environment": "development"}
{"timestamp": "2024-12-01T15:16:31.027296", "level": "ERROR", "message": "Error in admin_add_property: 1265 (01000): Data truncated for column 'status' at row 1", "module": "admin", "function": "admin_add_property", "line": 450, "thread_id": 134495607871296, "environment": "development", "exception": {"type": "DatabaseError", "message": "1265 (01000): Data truncated for column 'status' at row 1", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Data truncated for column 'status' at row 1\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 391, in admin_add_property\n    property_id_result = execute_procedure(\n                         ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'status' at row 1"}}
{"timestamp": "2024-12-01T15:16:40.340754", "level": "ERROR", "message": "Error in admin_add_property: 1265 (01000): Data truncated for column 'status' at row 1", "module": "admin", "function": "admin_add_property", "line": 450, "thread_id": 134495607871296, "environment": "development", "exception": {"type": "DatabaseError", "message": "1265 (01000): Data truncated for column 'status' at row 1", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Data truncated for column 'status' at row 1\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 391, in admin_add_property\n    property_id_result = execute_procedure(\n                         ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'status' at row 1"}}
{"timestamp": "2024-12-01T15:16:41.102144", "level": "ERROR", "message": "Error in admin_add_property: 1265 (01000): Data truncated for column 'status' at row 1", "module": "admin", "function": "admin_add_property", "line": 450, "thread_id": 134495607871296, "environment": "development", "exception": {"type": "DatabaseError", "message": "1265 (01000): Data truncated for column 'status' at row 1", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Data truncated for column 'status' at row 1\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 391, in admin_add_property\n    property_id_result = execute_procedure(\n                         ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'status' at row 1"}}
{"timestamp": "2024-12-01T15:16:47.116975", "level": "ERROR", "message": "Error in admin_add_property: 1265 (01000): Data truncated for column 'status' at row 1", "module": "admin", "function": "admin_add_property", "line": 450, "thread_id": 134495607871296, "environment": "development", "exception": {"type": "DatabaseError", "message": "1265 (01000): Data truncated for column 'status' at row 1", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Data truncated for column 'status' at row 1\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 391, in admin_add_property\n    property_id_result = execute_procedure(\n                         ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'status' at row 1"}}
{"timestamp": "2024-12-01T21:10:00.798726", "level": "ERROR", "message": "Error creating property: 1265 (01000): Data truncated for column 'status' at row 1", "module": "admin", "function": "admin_add_property", "line": 442, "thread_id": 132359979312960, "environment": "development", "exception": {"type": "DatabaseError", "message": "1265 (01000): Data truncated for column 'status' at row 1", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Data truncated for column 'status' at row 1\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 387, in admin_add_property\n    property_result = execute_procedure(\n                      ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'status' at row 1"}}
{"timestamp": "2024-12-01T21:14:06.295691", "level": "ERROR", "message": "Error creating property: 1265 (01000): Data truncated for column 'status' at row 1", "module": "admin", "function": "admin_add_property", "line": 442, "thread_id": 132359979312960, "environment": "development", "exception": {"type": "DatabaseError", "message": "1265 (01000): Data truncated for column 'status' at row 1", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Data truncated for column 'status' at row 1\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 387, in admin_add_property\n    property_result = execute_procedure(\n                      ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'status' at row 1"}}
{"timestamp": "2024-12-01T21:14:47.774707", "level": "ERROR", "message": "Error creating property: 1265 (01000): Data truncated for column 'p_status' at row 1", "module": "admin", "function": "admin_add_property", "line": 442, "thread_id": 132359979312960, "environment": "development", "exception": {"type": "DatabaseError", "message": "1265 (01000): Data truncated for column 'p_status' at row 1", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Data truncated for column 'p_status' at row 1\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 387, in admin_add_property\n    property_result = execute_procedure(\n                      ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'p_status' at row 1"}}
{"timestamp": "2024-12-01T21:17:28.596983", "level": "ERROR", "message": "Error creating property: 1265 (01000): Data truncated for column 'p_status' at row 1", "module": "admin", "function": "admin_add_property", "line": 442, "thread_id": 132359979312960, "environment": "development", "exception": {"type": "DatabaseError", "message": "1265 (01000): Data truncated for column 'p_status' at row 1", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Data truncated for column 'p_status' at row 1\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 387, in admin_add_property\n    property_result = execute_procedure(\n                      ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'p_status' at row 1"}}
{"timestamp": "2024-12-01T21:19:43.828122", "level": "ERROR", "message": "Error fetching properties: 1305 (42000): PROCEDURE real_estate.get_all_properties_with_details does not exist", "module": "main", "function": "index", "line": 36, "thread_id": 132280709097280, "environment": "development"}
{"timestamp": "2024-12-01T21:19:45.146252", "level": "ERROR", "message": "Error fetching properties: 1305 (42000): PROCEDURE real_estate.get_all_properties_with_details does not exist", "module": "main", "function": "index", "line": 36, "thread_id": 132280709097280, "environment": "development"}
{"timestamp": "2024-12-01T22:14:30.871311", "level": "ERROR", "message": "Error fetching listings: 1054 (42S22): Unknown column 'al.agent_name' in 'field list'", "module": "main", "function": "index", "line": 48, "thread_id": 129377474914112, "environment": "development"}
{"timestamp": "2024-12-01T22:16:36.471266", "level": "ERROR", "message": "Error fetching listings: 1054 (42S22): Unknown column 'al.agent_name' in 'field list'", "module": "main", "function": "index", "line": 48, "thread_id": 129377474914112, "environment": "development"}
{"timestamp": "2024-12-01T22:16:37.663322", "level": "ERROR", "message": "Error fetching listings: 1054 (42S22): Unknown column 'al.agent_name' in 'field list'", "module": "main", "function": "index", "line": 48, "thread_id": 129377474914112, "environment": "development"}
{"timestamp": "2024-12-01T22:18:22.971374", "level": "ERROR", "message": "Error fetching listings: 1054 (42S22): Unknown column 'al.agent_name' in 'field list'", "module": "main", "function": "index", "line": 48, "thread_id": 128612687603520, "environment": "development"}
{"timestamp": "2024-12-01T22:20:05.087905", "level": "ERROR", "message": "Error fetching listings: 1054 (42S22): Unknown column 'al.agent_name' in 'field list'", "module": "main", "function": "index", "line": 48, "thread_id": 128612687603520, "environment": "development"}
{"timestamp": "2024-12-01T22:20:06.350246", "level": "ERROR", "message": "Error fetching listings: 1054 (42S22): Unknown column 'al.agent_name' in 'field list'", "module": "main", "function": "index", "line": 48, "thread_id": 128612687603520, "environment": "development"}
{"timestamp": "2024-12-01T22:21:01.731825", "level": "ERROR", "message": "Error fetching listings: 1054 (42S22): Unknown column 'al.agent_name' in 'field list'", "module": "main", "function": "index", "line": 48, "thread_id": 138430225073984, "environment": "development"}
{"timestamp": "2024-12-01T22:21:03.131639", "level": "ERROR", "message": "Error fetching listings: 1054 (42S22): Unknown column 'al.agent_name' in 'field list'", "module": "main", "function": "index", "line": 48, "thread_id": 138430225073984, "environment": "development"}
{"timestamp": "2024-12-01T22:21:10.574720", "level": "ERROR", "message": "Error fetching listings: 1054 (42S22): Unknown column 'al.agent_name' in 'field list'", "module": "main", "function": "index", "line": 48, "thread_id": 138430225073984, "environment": "development"}
{"timestamp": "2024-12-01T22:23:29.740110", "level": "ERROR", "message": "Error fetching listings: 1054 (42S22): Unknown column 'al.client_phone' in 'field list'", "module": "main", "function": "index", "line": 48, "thread_id": 125900266850112, "environment": "development"}
{"timestamp": "2024-12-01T22:23:35.313627", "level": "ERROR", "message": "Error fetching listings: 1054 (42S22): Unknown column 'al.client_phone' in 'field list'", "module": "main", "function": "index", "line": 48, "thread_id": 125900266850112, "environment": "development"}
{"timestamp": "2024-12-01T22:24:39.714003", "level": "ERROR", "message": "Error fetching listings: 1054 (42S22): Unknown column 'al.l_agent_role' in 'field list'", "module": "main", "function": "index", "line": 48, "thread_id": 129173092489024, "environment": "development"}
{"timestamp": "2024-12-01T22:25:44.111738", "level": "ERROR", "message": "Error fetching listings: 1054 (42S22): Unknown column 'cp.tax_id' in 'on clause'", "module": "main", "function": "index", "line": 48, "thread_id": 138182163584832, "environment": "development"}
{"timestamp": "2024-12-01T22:28:03.346517", "level": "ERROR", "message": "Error fetching listings: 1305 (42000): PROCEDURE real_estate.debug_tables_data does not exist", "module": "main", "function": "index", "line": 46, "thread_id": 136488713295680, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.debug_tables_data does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.debug_tables_data does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/main.py\", line 27, in index\n    debug_info = execute_procedure(conn, \"debug_tables_data\")\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.debug_tables_data does not exist"}}
{"timestamp": "2024-12-01T22:30:40.846258", "level": "ERROR", "message": "Integrity error: 1062 (23000): Duplicate entry '3482348' for key 'Agent.NRDS'", "module": "admin", "function": "create_agent", "line": 297, "thread_id": 128959063717696, "environment": "development", "exception": {"type": "IntegrityError", "message": "1062 (23000): Duplicate entry '3482348' for key 'Agent.NRDS'", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Duplicate entry '3482348' for key 'Agent.NRDS'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 273, in create_agent\n    agent_id_result = execute_procedure(\n                      ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry '3482348' for key 'Agent.NRDS'"}}
{"timestamp": "2024-12-01T22:30:43.881613", "level": "ERROR", "message": "Integrity error: 1062 (23000): Duplicate entry '3482348' for key 'Agent.NRDS'", "module": "admin", "function": "create_agent", "line": 297, "thread_id": 128959063717696, "environment": "development", "exception": {"type": "IntegrityError", "message": "1062 (23000): Duplicate entry '3482348' for key 'Agent.NRDS'", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Duplicate entry '3482348' for key 'Agent.NRDS'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 273, in create_agent\n    agent_id_result = execute_procedure(\n                      ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry '3482348' for key 'Agent.NRDS'"}}
{"timestamp": "2024-12-01T22:30:47.094657", "level": "ERROR", "message": "Integrity error: 1062 (23000): Duplicate entry '3482348' for key 'Agent.NRDS'", "module": "admin", "function": "create_agent", "line": 297, "thread_id": 128959063717696, "environment": "development", "exception": {"type": "IntegrityError", "message": "1062 (23000): Duplicate entry '3482348' for key 'Agent.NRDS'", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Duplicate entry '3482348' for key 'Agent.NRDS'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 273, in create_agent\n    agent_id_result = execute_procedure(\n                      ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry '3482348' for key 'Agent.NRDS'"}}
{"timestamp": "2024-12-01T22:34:36.273243", "level": "ERROR", "message": "Error fetching property 1: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "module": "properties", "function": "property_detail", "line": 59, "thread_id": 126016681211712, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_property_by_tax_id does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/properties.py\", line 50, in property_detail\n    property = execute_procedure(conn, \"get_property_by_tax_id\", (tax_id,))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist"}}
{"timestamp": "2024-12-01T22:34:37.176376", "level": "ERROR", "message": "Error fetching property 1: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "module": "properties", "function": "property_detail", "line": 59, "thread_id": 126016681211712, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_property_by_tax_id does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/properties.py\", line 50, in property_detail\n    property = execute_procedure(conn, \"get_property_by_tax_id\", (tax_id,))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist"}}
{"timestamp": "2024-12-01T22:34:37.758913", "level": "ERROR", "message": "Error fetching property 1: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "module": "properties", "function": "property_detail", "line": 59, "thread_id": 126016681211712, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_property_by_tax_id does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/properties.py\", line 50, in property_detail\n    property = execute_procedure(conn, \"get_property_by_tax_id\", (tax_id,))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist"}}
{"timestamp": "2024-12-01T22:34:38.345771", "level": "ERROR", "message": "Error fetching property 1: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "module": "properties", "function": "property_detail", "line": 59, "thread_id": 126016681211712, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_property_by_tax_id does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/properties.py\", line 50, in property_detail\n    property = execute_procedure(conn, \"get_property_by_tax_id\", (tax_id,))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist"}}
{"timestamp": "2024-12-01T22:34:47.135849", "level": "ERROR", "message": "Error fetching property 1: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "module": "properties", "function": "property_detail", "line": 59, "thread_id": 140427210491712, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_property_by_tax_id does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/properties.py\", line 50, in property_detail\n    property = execute_procedure(conn, \"get_property_by_tax_id\", (tax_id,))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist"}}
{"timestamp": "2024-12-01T22:34:47.334918", "level": "ERROR", "message": "Error fetching property 1: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "module": "properties", "function": "property_detail", "line": 59, "thread_id": 140427210491712, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_property_by_tax_id does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/properties.py\", line 50, in property_detail\n    property = execute_procedure(conn, \"get_property_by_tax_id\", (tax_id,))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist"}}
{"timestamp": "2024-12-01T22:34:48.065610", "level": "ERROR", "message": "Error fetching property 1: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "module": "properties", "function": "property_detail", "line": 59, "thread_id": 140427210491712, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_property_by_tax_id does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/properties.py\", line 50, in property_detail\n    property = execute_procedure(conn, \"get_property_by_tax_id\", (tax_id,))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist"}}
{"timestamp": "2024-12-01T22:39:19.379842", "level": "ERROR", "message": "Error fetching property 1: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "module": "properties", "function": "property_detail", "line": 59, "thread_id": 132893362661184, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_property_by_tax_id does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/properties.py\", line 50, in property_detail\n    property = execute_procedure(conn, \"get_property_by_tax_id\", (tax_id,))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist"}}
{"timestamp": "2024-12-01T22:39:20.443345", "level": "ERROR", "message": "Error fetching property 1: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "module": "properties", "function": "property_detail", "line": 59, "thread_id": 132893362661184, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_property_by_tax_id does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/properties.py\", line 50, in property_detail\n    property = execute_procedure(conn, \"get_property_by_tax_id\", (tax_id,))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist"}}
{"timestamp": "2024-12-01T22:41:24.307236", "level": "ERROR", "message": "Error fetching property 1: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "module": "properties", "function": "property_detail", "line": 59, "thread_id": 132893362661184, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.get_property_by_tax_id does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/properties.py\", line 50, in property_detail\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 50, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.get_property_by_tax_id does not exist"}}
